@extends('client.layouts.layout')
@section('title')
    <title>Apparel Importers Data - Terms of Use</title>
@endsection

@section('metta')
    <meta name="description" content="An ISO 9001:2015 Certified Company" />
    <meta name="google-site-verification" content="Hz6qT2wnuYPGtIv9NAoMFLeKd6vHhRs8sKz76gVPrPE" />
    <meta name="keywords" content="panama, peru, philippines, poland, importers from portugal garments, qatar, apparel importers republica dominicana , romania, clothing russia buyers, san diego, saudi arabia, serbia, singapore/>
@endsection

@section('contents')
        </section><section class="w3l-job-overview1 mt-5">
    <div class="header-view py-5 pt-5">
        <div class="container pt-3">
            <div class="row align-items-center">
                <div class="col-md-8">
                    <h3 class="my-3">Privacy Statement</h3>

                    </ul>
                </div>
                <div class="col-md-4 job-apply mt-md-0 mt-4 text-md-right">
                </div>
            </div>
        </div>
    </div>
    </section>
    <section class="w3l-job-overview2 py-5">
        <div class="container">
            <div class="job-info mb-5">
                <p class="c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      When you purchase something from our store, as part of the buying and
      selling process, we collect the personal information you give us such as
      your name, address and email address.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      When you browse our store, we also automatically receive your computer's
      internet protocol (IP) address in order to provide us with information
      that helps us learn about your browser and operating system.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      Email Marketing : With your permission, we may send you emails about our
      store, new products and other updates.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 2 - CONSENT</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      How do you get my consent?</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      When you provide us with personal information to complete a transaction,
      verify your credit card, place an order, arrange for a delivery or return
      a purchase, we imply that you consent to our collecting it and using it
      for that specific reason only.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      If we ask for your personal information for a secondary reason, like
      marketing, we will either ask you directly for your expressed consent, or
      provide you with an opportunity to say no.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      How do I withdraw my consent?</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c6" style="font-weight: 400; font-family: Arial">If after you
      opt-in, you change your mind, you may withdraw your consent for us to
      contact you, for the continued collection, use or disclosure of your
      information, at anytime, by contacting us at&nbsp;</span><span class="c1"><span style="font-family: Arial">support@apparelimportersdata.com.</span></span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 3 - DISCLOSURE</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      We may disclose your personal information if we are required by law to do
      so or if you violate our Terms of Service.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 4 - PAYMENT</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      We use Razorpay for processing payments. We/Razorpay do not store your
      card data on their servers. The data is encrypted through the Payment Card
      Industry Data Security Standard (PCI-DSS) when processing payment. Your
      purchase transaction data is only used as long as is necessary to complete
      your purchase transaction. After that is complete, your purchase
      transaction information is not saved.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      Our payment gateway adheres to the standards set by PCI-DSS as managed by
      the PCI Security Standards Council, which is a joint effort of brands like
      Visa, MasterCard, American Express and Discover.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      PCI-DSS requirements help ensure the secure handling of credit card
      information by our store and its service providers.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c6" style="font-weight: 400; font-family: Arial">For more
      insight, you may also want to read terms and conditions of razorpay on&nbsp;</span><span class="c6 c10" style="color: rgb(17, 85, 204); text-decoration: underline; text-decoration-skip-ink: none; font-weight: 400; font-family: Arial"><a class="c5" href="https://www.google.com/url?q=https://razorpay.com&sa=D&ust=1594142492177000&usg=AOvVaw2hhkzvsNgRPYSJtK7YqsWu" style="color: inherit; text-decoration: inherit">https://razorpay.com</a></span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 5 - THIRD-PARTY SERVICES</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      In general, the third-party providers used by us will only collect, use
      and disclose your information to the extent necessary to allow them to
      perform the services they provide to us.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      However, certain third-party service providers, such as payment gateways
      and other payment transaction processors, have their own privacy policies
      in respect to the information we are required to provide to them for your
      purchase-related transactions.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      For these providers, we recommend that you read their privacy policies so
      you can understand the manner in which your personal information will be
      handled by these providers.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      In particular, remember that certain providers may be located in or have
      facilities that are located a different jurisdiction than either you or
      us. So if you elect to proceed with a transaction that involves the
      services of a third-party service provider, then your information may
      become subject to the laws of the jurisdiction(s) in which that service
      provider or its facilities are located.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      Once you leave our store's website or are redirected to a third-party
      website or application, you are no longer governed by this Privacy Policy
      or our website's Terms of Service.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      Links</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      When you click on links on our store, they may direct you away from our
      site. We are not responsible for the privacy practices of other sites and
      encourage you to read their privacy statements.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 6 - SECURITY</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      To protect your personal information, we take reasonable precautions and
      follow industry best practices to make sure it is not inappropriately
      lost, misused, accessed, disclosed, altered or destroyed.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 7 - COOKIES</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      We use cookies to maintain session of your user. It is not used to
      personally identify you on other websites.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 8 - AGE OF CONSENT</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      By using this site, you represent that you are at least the age of
      majority in your state or province of residence, or that you are the age
      of majority in your state or province of residence and you have given us
      your consent to allow any of your minor dependents to use this site.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      SECTION 9 - CHANGES TO THIS PRIVACY POLICY</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      We reserve the right to modify this privacy policy at any time, so please
      review it frequently. Changes and clarifications will take effect
      immediately upon their posting on the website. If we make material changes
      to this policy, we will notify you here that it has been updated, so that
      you are aware of what information we collect, how we use it, and under
      what circumstances, if any, we use and/or disclose it.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      If our store is acquired or merged with another company, your information
      may be transferred to the new owners so that we may continue to sell
      products to you.</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      QUESTIONS AND CONTACT INFORMATION</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c6" style="font-weight: 400; font-family: Arial">If you would
      like to: access, correct, amend or delete any personal information we have
      about you, register a complaint, or simply want more information contact
      our Privacy Compliance Officer at</span><span class="c1" style="font-weight: 700; font-family: Arial">
      support@apparelimportersdata.com</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      [Re: Privacy Compliance Officer]</span></p>
                <p class="c0 c3" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">&nbsp;</p>
                <p class="c0" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Open Sans; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; padding-top: 0pt; padding-bottom: 0pt">
      <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 11pt; font-family: Arial; font-style: normal">
      ----</span></div>
        </div>
    </section>
@endsection
